namespace ProjectEclipse.Progression
{
    public enum ResourceTier
    {
        Wood,
        Stone,
        Coal,
        Copper,
        Iron,
        Gold,
        Moon,
        Mars,
        Cosmic,
        Elemental,
        Tin,
        Bronze,
        Zinc,
        Brass,
        Steel,
        Silver,
        Cobalt,
        Mithril,
        Adamant,
        Titanium,
        Crystal,
        Gem,
        Arcane,
        Celestial
    }
}
